<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.instanto</groupId>
    <artifactId>domino-widgets-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>domino-widgets-gwt</artifactId>
  <dependencies>
    <dependency>
      <groupId>org.gwtproject</groupId>
      <artifactId>gwt-user</artifactId>
      <version>${gwt.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.instanto</groupId>
      <artifactId>gwt-modular-services</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-core</artifactId>
      <version>1.2.3</version>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-dom</artifactId>
      <version>1.2.3</version>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-svg</artifactId>
      <version>1.2.3</version>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-webstorage</artifactId>
      <version>1.2.3</version>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-promise</artifactId>
      <version>1.2.3</version>
    </dependency>
    <dependency>
      <groupId>com.google.jsinterop</groupId>
      <artifactId>jsinterop-annotations</artifactId>
      <version>2.0.2</version>
    </dependency>
    <dependency>
      <groupId>com.google.jsinterop</groupId>
      <artifactId>base</artifactId>
      <version>1.0.1</version>
    </dependency>
    <dependency>
      <groupId>org.gwtproject.core</groupId>
      <artifactId>gwt-core</artifactId>
      <version>1.0.0-RC1</version>
    </dependency>
    <dependency>
      <groupId>org.dominokit</groupId>
      <artifactId>domino-slf4j-logger</artifactId>
      <version>1.0.2</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <implicit>none</implicit>
          <excludes>
            <exclude>org/gwtproject/**</exclude>
          </excludes>
        </configuration>
      </plugin>
    </plugins>
    <sourceDirectory>../target/intake/gwt-widgets</sourceDirectory>
    <resources>
      <resource>
        <directory>../target/intake/gwt-widgets</directory>
        <excludes>
          <exclude>org/gwtproject/**</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>../target/intake/resources</directory>
        <excludes>
          <exclude>org/gwtproject/**</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>..</directory>
        <includes>
          <include>LICENSE</include>
          <include>NOTICE</include>
          <include>upstream/source-lock.json</include>
        </includes>
        <targetPath>META-INF</targetPath>
      </resource>
    </resources>
  </build>
</project>
